# Generated by Django 5.1.7 on 2025-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobil',
            name='matricula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
