# Generated by Django 5.1.7 on 2025-03-28 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0002_alter_automobil_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField()),
                ('automobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lloguer.automobil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('automobil', 'data_inici')},
            },
        ),
    ]
